language: python
python:
- 2.6
- 2.7
sudo: false
cache:
  directories:
  - eggs
env:
- ZOPE_VERSION=2.13.22
matrix:
  fast_finish: true
install:
- sed -ie "s#2.13.22/versions.cfg#$ZOPE_VERSION/versions.cfg#" buildout.cfg
- python bootstrap.py
- bin/buildout annotate
- bin/buildout -Nq
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- bin/code-analysis
- bin/test
after_success:
- bin/createcoverage
- pip install -q coveralls
- coveralls
